[package]
name = "benchfx"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"